### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by johnbradley** [hdr-bgnn/minnowTraits#10]
Add a license to this repo. The typical convention is just to add a text file named LICENSE.
See https://github.com/hdr-bgnn/BGNN_Snakemake/issues/2#issue-1165804632 for some good options to help choosing a license.

**Comment by meghalithic** [comment]
@johnbradley do you have an example of a license file?

**Comment by thibaulttabarin** [comment]
I will show you how to do it tomorrow

**Comment by johnbradley** [comment]
You can see the LICENSE file in BGNN_Snakemake: https://github.com/hdr-bgnn/BGNN_Snakemake/blob/main/LICENSE
GitHub makes it really easy to add a LICENSE file once you have decided on one: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by thibaulttabarin** [comment]
I am convinced we should use MIT license, the same I have used for all the repo where are using on hdr-BGNN

**Comment by meghalithic** [comment]
I can get onboard with that, that's what some of my other projects use
