### ISSUE TITLE
Download input files from dataverse

### ISSUE THREAD

**Issue by johnbradley** [hdr-bgnn/minnowTraits#27]
To improve metadata for input files we are storing them in the https://datacommons.tdai.osu.edu/ Dataverse.
Add steps to download the input files from Dataverse.

**Comment by johnbradley** [comment]
@hlapp @megbalk 
In our meeting yesterday we discussed the issue where Dataverse will post-process CSV files into TSV files.
The plan was to switch the workflow to use TSV instead of CSV to avoid this issue. Unfortunately it looks like the ingress processing always occurs even for TSV files. If you happen to match the formatting that Dataverse uses for the TSV file (adding quotes around some columns) there is no issue with downloading (ie md5 matches). I'm wondering if we should just stick with CSV and add further logic to the downloading code to fetch the original file.

**Comment by hlapp** [comment]
Ah that's even more messed up than I thought. (cc'ing @chang-osu-136 so he's aware of this)

I agree, in this case there seems to be no easy workaround, and we should probably just have code that expects and deals with the CSV issue. I do think it's important to maintain an MD5 integrity check for the download, it's a core best practice for data traceability.

**Comment by hlapp** [comment]
BTW does this need to be an issue for here or for the [dataverse-access](https://github.com/Imageomics/dataverse-access) repo?

**Comment by johnbradley** [comment]
Here is the issue for the `Hash value mismatch` error when trying to download a TSV file: https://github.com/Imageomics/dataverse-access/issues/6

**Comment by meghalithic** [comment]
@johnbradley so don't upload tsv?

**Comment by johnbradley** [comment]
> @johnbradley so don't upload tsv?

@megbalk There is no need to switch to TSV and upload. Dataverse will even duplicate TSV files. You can end up with two TSV files with slightly different formatting. 

I updated the code that downloads data to work around this "feature" and retrieve the file that was originally uploaded.
I have a branch that downloads the three input CSV files you previously uploaded  to Dataverse:
https://github.com/hdr-bgnn/Minnow_Traits/compare/dataverse-download
In that branch I still need to update documentation on how to setup the configuration for Dataverse.
Since the CSV files are not published users will need to provide a key for authentication with Dataverse.

**Comment by meghalithic** [comment]
@johnbradley can this issue be closed then?

**Comment by johnbradley** [comment]
> @johnbradley can this issue be closed then?

I setup PR #29 to automatically close this issue when merged. If you are good with the changes you can merge that PR. That PR adds a manual step to the README where users need to setup their Dataverse API Token: https://github.com/hdr-bgnn/Minnow_Traits/blob/50cde9f0dc48d7975c09cd34abf391bdec0229bc/README.md#dataverse-configuration
This step is needed since the input CSV files are not published.
