### ISSUE TITLE
Should we preserve plots

### ISSUE THREAD

**Issue by johnbradley** [hdr-bgnn/minnowTraits#5]
The selectionCriteriaSegmentedImages.R script writes out a `presence.absence.matrix.csv` file. This R code also creates several plots. For example:

https://github.com/hdr-bgnn/minnowTraits/blob/686113ec48bff0a990314b23720e299e237871f9/Scripts/selectionCriteriaSegmentedImages.R#L251-L261

Do these plots need to be persisted? Or are they merely diagnostic from when this code was being developed.

**Comment by johnbradley** [comment]
Thoughts @megbalk ?

**Comment by meghalithic** [comment]
I may put them in the supplemental materials as justification for our selection criteria.

**Comment by johnbradley** [comment]
If they are supplemental materials we should probably save them then. Would saving them as images be best? Alternatively we could create a R markdown file and convert it into a suitable output file.

**Comment by meghalithic** [comment]
I can save directly from the code. It's still a work in progress, though.
